ScreenOrientation + Spago support
keijokapp/purescript-web-cssom-view pull request #2
Opened 2021-11-10 08:40 UTC by toastal

W3 spec for `ScreenOrientation`: https://drafts.csswg.org/cssom-view/

Also including support for Spago and its package sets

2022-01-30 11:01 UTC, keijokapp requested changes
Thanks for the PR!

Sorry for not reviewing that earlier. I haven't used purescript for over a year and don't see myself using it within foreseeable future. I don't have a test project to test these changes. I guess they are okay.

One big question is about the addition of Spago setup. Seems that Spago is still used only for applications, not libraries like this one. I looked at some other purescript-web packages and they don't have Spago setup. So I guess, you should remove it from the PR.

2022-01-30 11:01 UTC, keijokapp commented on .gitignore
> +.purs-repl
1. I'm not sure, but I think that `.purs-repl` and `dce-output` shouldn't be in shared `.gitignore`. These seem to be specific to a particular development environment and/or developer. I recommend adding such kind of files to `.git/info/exclude`.

1. `.gitignore` entries should start with a `/` whenever possible. That way, we don't have to worry about recursive matches and confusion that might come with it.

2. I'd prefer to _not_ have a trailing `/` at the end of any `.gitignore` entry. There's no relevant benefits for a slash, except maybe for documenting the tree structure but I don't think anyone needs that documentation.

2022-01-30 11:01 UTC, keijokapp commented on src/Web/CSSOMView/ScreenOrientation.js
> +/* Web.CSSOMView.ScreenOrientation */
That comment is unneccessary. The module name is already known from the file name.

2022-01-30 11:01 UTC, keijokapp commented on src/Web/CSSOMView/ScreenOrientation.js
> +      so.lock(orientation).then(onSuccess).catch(onError);
A small nitpick, but `.then` has a 2-argument variant for exactly this use case. The code would be
```js
so.lock(orientation).then(onSuccess, onError);
```

2022-02-01 06:02 UTC, toastal commented
Updated

2022-02-05 22:37 UTC, merged

2022-02-05 22:37 UTC, keijokapp commented
Thank you!